### ISSUE TITLE
Add midi support to vial's json, what should I write? Is there an example in keyboards?

### ISSUE THREAD

**Issue by jeromeli002** [vial-kb/vial-qmk#207]
Add midi support to vial's json, what should I write? Is there an example in keyboards? Where is it added?

![image](https://user-images.githubusercontent.com/5648129/179438349-c7aaaff1-7121-4e74-aed3-5016ce6e642e.png)

**Comment by xyzz** [comment]
You don't need to add anything other than the `midi` field; here's an example: https://github.com/vial-kb/vial-qmk/blob/868908ad8a0fe2fc6f0b7a1d41813ff3ddd64c28/keyboards/planck/ez/glow/keymaps/vial/vial.json#L7-L9
