### ISSUE TITLE
gitignore via*.json

### ISSUE THREAD

**Issue by GerritPlehn** [vial-kb/vial-qmk#212]
Since the last merge of upstream QMK, VIA and Vial JSON files have been added to the gitignore.
https://github.com/vial-kb/vial-qmk/blob/d399418f758693c44040a4d00689c66ba42f01af/.gitignore#L99
This is pretty inconvenient when maintaining keyboards as changes need to be staged manually every time.
```sh
git add vial.json -f
```
Can we remove this line from the gitignore to make our lives easier?

**Comment by xyzz** [comment]
874e867764716c1182690f7607fe1305cf06da0a
