### ISSUE TITLE
More Macros/Layers

### ISSUE THREAD

**Issue by DomTripodi93** [vial-kb/vial-qmk#226]
Just started using this on a new keyboard, and after 15 macros there is no way to add more. 

I'm not sure if this is already something someone is working on, but I was hoping to use more macros than that - like 40+ for CLI command shortcuts.

Similar story with layers, I was hoping to have 4 or 5 layers just for those commands shortcuts and then other ones for symbols and normal things like that.

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

With QMK I could write unlimited macros and layers, even with configurator you would get 15 layers, and some of the settings in vial refer to those additional layers, so maybe I'm just missing a way to pass that to the vial GUI, or some backdoor that goes around the GUI. 

![image](https://user-images.githubusercontent.com/44410886/185679293-40d15c8c-52d2-4b66-8f0f-cab3ba6110fb.png)

**Comment by xyzz** [comment]
Please file feature requests at https://feedback.vial.today/
