### ISSUE TITLE
Implement Leader Key from QMK

### ISSUE THREAD

**Issue by hiszd** [vial-kb/vial-qmk#277]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

The leader key function that exists in the QMK main branch implemented inside of Vial
Documentation here: [QMK Leader Key](https://docs.qmk.fm/#/feature_leader_key)

**Comment by xyzz** [comment]
Please use https://feedback.vial.today/ for feature requests
