### ISSUE TITLE
[Feature Request] Add support for the Keychron K2 V2.

### ISSUE THREAD

**Issue by ghost** [vial-kb/vial-qmk#293]
The keychron K2 V2 is supported by the sonixQMK branch, please add support for this keyboard in Vial. 

## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
The Keychron K2/K2V2 is supported on the SonixQMK branch and is also supported on VIA from their branch, Vial works for keymapping and macro with the via sideload option, but no RGB control. I'm open to provide any help needed as I own this specific keyboard.

**Comment by xyzz** [comment]
Please file feature requests to https://feedback.vial.today/
