### ISSUE TITLE
[Bug] Currently-shipping Libra Mini boards not detectable by Vial due to changed productId

### ISSUE THREAD

**Issue by sehrgut** [vial-kb/vial-qmk#377]
## Describe the Bug
The Libra Mini definition in Vial expects productId 0x4C24, but currently-shipping boards have productId 0x4C23. The existing definition is otherwise fully compatible with 0x4C23 boards.

## System Information

**Keyboard:** Libra Mini
**Revision (if applicable):** 0x4C23 putative rev.  2
**Operating system:** n/a
**`qmk doctor` output:** n/a

**Any keyboard related software installed?** 
n/a

## Additional Context
Files currently working with 0x4C23 boards: https://gist.github.com/sehrgut/622edc0f0e3a75bcff367c4cff2a436a

**Comment by xyzz** [comment]
Vial doesn't actually use vendorId or productId for the vial firmware. It is only used in VIA backwards compatibility mode. So if the keyboard's not showing up, that means it was not flashed with the vial firmware. In general I consider VIA backwards compatibility to be mostly deprecated, so we will not act on this issue.

My suggestions are:
- check with the keyboard vendor if the Vial firmware is available for that keyboard, download and flash it
- consider using the VIA application for keyboards flashed with VIA firmware
