### ISSUE TITLE
[Feature Request] Apply Joystick improvements from upstream qmk

### ISSUE THREAD

**Issue by 9R** [vial-kb/vial-qmk#384]
## Feature Request Type

- [x] Core functionality
- [x] Improve hardware support: Joystick
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

QMK merged some improvements for the joystick implementation in January:  qmk/qmk_firmware#19052

This changed some variables which makes it harder to maintain configurations for qmk and qmk-vial.

Because of these changes following current QMK documentation on how to implement joysticks does not work with Vial any more and will result in failed builds and there is no Vial-specific documentation describing the current implementation in vial. This currently makes it harder to port new devices with Joysticks or analog inputs to Vial.

Here is a summary of improvements copied from the original pull requests:
   - Improved documentation, added API reference
   - Renamed JOYSTICK_AXES_COUNT/JOYSTICK_AXES_RESOLUTION to singular AXIS to align with JOYSTICK_BUTTON_COUNT
   - Replaced enum joystick_status with simple dirty flag in joystick_t
   - Added V-USB support
   - Added shared EP support for LUFA/ChibiOS

Is it possible to merge these changes in Vial?

**Comment by Cujo26** [comment]
Vial periodically merges changes from upstream, so new features should get implemented, just on a bit of a delay compared to the main project.

**Comment by lesshonor** [comment]
If this is very important to you, you can help test the (current as of June 6) beta merge branch on your keyboard's hardware, which incorporates these updates and many more: https://github.com/vial-kb/vial-qmk/tree/merge-2023-06-03

You will need a new version of the GUI to work with any firmware from this branch: https://github.com/vial-kb/vial-gui/actions/runs/5108218697

**Comment by 9R** [comment]
Sorry for the long response time on my end. I have tested against current vial and the issue is not present any more.

I have also created a [PR](https://github.com/vial-kb/vial-qmk/pull/798) for the keyboard that is using this feature.
