### ISSUE TITLE
Issue with multiple pcb versions sharing a keymap folder

### ISSUE THREAD

**Issue by stanrc85** [vial-kb/vial-qmk#411]
I recently ported the Adelais rev4 PCB to Vial (https://github.com/vial-kb/vial-qmk/pull/408) and I'd like to do the same for the Adelais en ciel Rev3 PCB but I've run into an issue.  All the Adelais PCBs (both regular RGB and per key RGB) share the same keymap folder but each requires a unique vial.json file. I wouldn't be able to submit a PR for the Adelais en ciel PCB port without overwriting the vial.json for the other PCB. 

I can create the PR and submit if it that would help demonstrate the issue.

I'm not sure how common this is across QMK or if this is a one off.

**Comment by xyzz** [comment]
It is not an issue with vial; you just have to put the keymap under the specific "revX/keymaps" (which may not exist yet) and not under the general "keymaps" folder.
