### ISSUE TITLE
[Question] where do I enable set_unicode_input_mode?

### ISSUE THREAD

**Issue by isr** [vial-kb/vial-qmk#466]
I'm using the vial appimage, with an ergohaven k02 keyboard, and am unable to get unicode keycodes.

For reference, on an older keyboard (atreus62), I compile & apply qmk directly. In that keymap.c, I have the following:

```
void matrix_init_user(){
  set_unicode_input_mode(UC_LNX);
};
```

This enables me to use keycodes which emit unicode, eg: UC(0x03bb) gives "λ".

How do I configure this with vial?

Thanks in advance :)

**Comment by lesshonor** [comment]
Follow the instructions here to configure Unicode: https://github.com/vial-kb/vial-qmk/blob/vial/docs/feature_unicode.md

If you don't want to recompile, you could replicate unicode input by creating macros which trigger the appropriate keypresses for your OS—this is actually what QMK does [internally](https://github.com/vial-kb/vial-qmk/blob/vial/quantum/process_keycode/process_unicode_common.c).

If you would like to neatly assign these keycodes in the GUI, right now your only option is to [implement a custom keycode](https://get.vial.today/manual/custom_keycode.html)—that would let you call `send_unicode_string` or `register_unicode` and leverage the existing cross-OS handling.

**Comment by isr** [comment]
(sorry for the late response, just read this now)

Thanks for the info, I'll try this out.

**Comment by isr** [comment]
closing ...
