### ISSUE TITLE
Keymaps failing to build on merge-2023-06-03

### ISSUE THREAD

**Issue by xyzz** [vial-kb/vial-qmk#488]
These keymaps are currently failing to build on `merge-2023-06-03`. If we cannot fix them before the next merge (~2 weeks) they will be deleted from vial-qmk.

* [ ] `handwired/3dpcb` @jkutianski 
* [ ] `password` @ll3macorn
* [ ] `akb/vero` @rachmansyahbs
* [ ] `handwired/prkl30` @CountKeepo
* [ ] `hineybush/h60` @WrinkleKrinkles
* [ ] `ilumkb/primus75` @cebby2420
* [x] `keychron/q7/ansi` @adophoxia
* [ ] `planck/rev6_drop` @dijidiji
* [ ] `studiokestra/galatea` @WrinkleKrinkles

See https://github.com/vial-kb/vial-qmk/actions/runs/5305999907

**Comment by Ll3ma** [comment]
i havent touched qmk in way too long, what do i need to do to fix it
