### ISSUE TITLE
[Feature Request] In-memory buffer for tap dance storage

### ISSUE THREAD

**Issue by M3m3M4n** [vial-kb/vial-qmk#509]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

In the current source, vial tap dance is handled by reading ROM directly to fetch its data. Would it be faster, easier to customize (code wise) and less taxing on the eeprom if:
- Tap dance is stored in a buffer in RAM, only commited to eeprom if press "save to rom"
- Tap dance buffer is loaded from eeprom after initializtion, like using keyboard_post_init_user
- User can setup their own TD slot in code after its loaded

**Comment by xyzz** [comment]
Please submit feature requests to https://feedback.vial.today/
