### ISSUE TITLE
V87 PRO want running in vial

### ISSUE THREAD

**Issue by saulshpark** [vial-kb/vial-qmk#530]
I have a cidooo's V87pro 

I want to use tab dance
Unfortunately, however, via does not support that feature, but only vial.
So I'm going to flash with vial.
I prepared these three files, but there are errors.

how can I comfile and use vial?

[keymaps.zip](https://github.com/vial-kb/vial-qmk/files/12450906/keymaps.zip)
![error](https://github.com/vial-kb/vial-qmk/assets/143381211/ce6feab2-2c6b-400d-9a99-fb2125c78c3a)

**Comment by lesshonor** [comment]
Paraphrased from [the Vial porting guide](https://get.vial.today/docs/porting-to-vial.html):

> If you only have precompiled firmware, you will need to obtain the source code for the keyboard before you can port it to Vial. [You have the right to ask the maker of your keyboard for this](https://www.gnu.org/licenses/gpl-faq.en.html#ModifiedJustBinary).

...Good luck getting that source code, though; Epomaker is notoriously uncooperative.
