### ISSUE TITLE
Encoder direction arrow in VIAL GUI pointing in the wrong direction.

### ISSUE THREAD

**Issue by BenRoe** [vial-kb/vial-qmk#547]
With the current QMK firmware, they migrated the rotary encoder pin settings to the `info.json`.

```json
    "encoder": {
        "rotary": [{ "pin_a": "F5", "pin_b": "F4" }]
    },
    "split": {
        "enabled": true,
        "soft_serial_pin": "D2",
        "matrix_pins": {
            "right": {
                "cols": ["F6", "F7", "B1", "B3", "B2", "B6"],
                "rows": ["D4", "C6", "D7", "E6", "B4", "B5"]
            }
        },
        "encoder": {
            "right": {
                "rotary": [{ "pin_a": "F4", "pin_b": "F5" }]
            }
        }
    },
```

Does VIAL supports that too?

It's working, but i can't set for both half's a different setting.

I also have the problem, that the arrows in the VIAL GUI are flipped.
In my keymap i have 

```c
#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [_QWERTY] = { ENCODER_CCW_CW(KC_DOWN, KC_UP),          ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
    [_LOWER] =  { ENCODER_CCW_CW(RGB_HUI, KC_TAB),         ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [_RAISE] =  { ENCODER_CCW_CW(RGB_VAD, RGB_VAI),        ENCODER_CCW_CW(RGB_SPD, RGB_SPI) },
    [_ADJUST] = { ENCODER_CCW_CW(RGB_RMOD, RGB_MOD),       ENCODER_CCW_CW(RGB_SAD, RGB_SAI) },
    //                  Encoder 1                                     Encoder 2
};
#endif // ENCODER_MAP_ENABLE
```

Turning the encoder CCW on layer 1 turns the volume down and CW up.
But in the GUI the arrows pointing in the wrong direction.

<img width="1187" alt="Bildschirmfoto 2023-09-18 um 13 24 31" src="https://github.com/vial-kb/vial-qmk/assets/643834/6c0b2532-0c3b-4eb6-997c-31118befe6f7">

**Comment by lesshonor** [comment]
> Does VIAL supports that too?

Yes.

...You mention the encoder on the right side, but the other encoder is "backwards" too; according to your code, `KC_TAB` should be clockwise and `RGB_HUI` should be counter-clockwise, and in your screenshot it's the other way around.

At any rate, the encoder arrows will always be drawn CCW on the left and CW on the right.

**Comment by BenRoe** [comment]
Any suggestions how to fix the arrow pointing in the wrong direction?

**Comment by lesshonor** [comment]
Amend your `vial.json`?

**Comment by BenRoe** [comment]
> Amend your `vial.json`?

~~You can find the vial.json here.~~

https://github.com/Keycapsss/vial-qmk/blob/6236c4d087a22628057cbeecf26700bbb0695536/keyboards/keycapsss/kimiko/rev2/keymaps/vial/vial.json

Sorry this is not the up to date file.
Will push it on Friday.

**Comment by BenRoe** [comment]
@lesshonor here you can find my latest vial.json
https://github.com/Keycapsss/vial-qmk/blob/kimiko_rev2_dev/keyboards/keycapsss/kimiko/rev2/keymaps/vial/vial.json

**Comment by BenRoe** [comment]
The keyboard behaves correct.
If i turn the encoder on the right half CCW, the cursor moves left.

```c
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [_QWERTY] = { ENCODER_CCW_CW(KC_DOWN, KC_UP),          ENCODER_CCW_CW(KC_LEFT, KC_RGHT) },
```

But in the VIAL GUI the arrows pointing in the wrong direction. 
It's pointing CW for LEFT.

How can i fix that, or is that a VIAL bug? @lesshonor 

![Bildschirmfoto 2023-09-26 um 13 10 36](https://github.com/vial-kb/vial-qmk/assets/643834/a4ccc673-f915-45f7-85e3-86ecef14717b)

**Comment by BenRoe** [comment]
Thanks to tweetydabird and kiserdesigns ❤️  from the VIAL Discord Server i found the solution.

I had to flip [the encoder pin assignment](https://github.com/Keycapsss/vial-qmk/blob/16a19257d75399c24131b65c9762bdfdd6b5d2d0/keyboards/keycapsss/kimiko/rev2/info.json#L31-L48) in the info.json

**Important**
Before flashing the new firmware, do a `Clear EEPROM` on both half with QMK Toolbox.
