### ISSUE TITLE
key lock feature doesn't seem to work.

### ISSUE THREAD

**Issue by wangmeng99** [vial-kb/vial-qmk#564]
In Vial GUI I just set the keycode value to '0x5d2a' as mentioned in https://github.com/vial-kb/vial-gui/issues/86 but I didn't see any locking effect. I.e. press this key followed by pressing the second key (e.g. shift), the shift is not held.

I also tried '0x5d2b' as seen in this part of QMK code https://github.com/qmk/qmk_firmware/pull/18796/files#diff-a1e3db3da28dac00887cfe7f0f49aa739191483e1983f47ea96d77096f586038L474 which doesn't work either.

**Comment by lesshonor** [comment]
To make an [extremely long story](https://docs.qmk.fm/#/api_docs?id=qmk-constants) short, that's not the correct keycode.
https://github.com/vial-kb/vial-qmk/blob/f06a05a5d5e2e4e92d4ae28628cebaba2b9c32f0/quantum/keycodes.h#L704
