### ISSUE TITLE
STM32F103xB_stm32duino_bootloader.ld: No such file or directory

### ISSUE THREAD

**Issue by aluminum-ice** [vial-kb/vial-qmk#578]
I am trying to compile a [custom keymap for the DOIO KB16](https://github.com/aluminum-ice/kb16_rev2_vial_fw)  and I keep running into this issue that Google does not provide any useful information on:

```
Linking: .build/doio_kb16tv_rev2_vial.elf                                                           [ERRORS]
 |
 | /opt/homebrew/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ld: cannot open linker script file ./lib/chibios/os/common/startup/ARMCMx/compilers/GCC/ld/STM32F103xB_stm32duino_bootloader.ld: No such file or directory
 | collect2: error: ld returned 1 exit status
 |
gmake[1]: *** [builddefs/common_rules.mk:271: .build/doio_kb16tv_rev2_vial.elf] Error 1
Make finished with errors
gmake: *** [Makefile:392: doio/kb16tv/rev2:vial] Error 1
```

It seems like there use to be a linker called `STM32F103xB_stm32duino_bootloader` that no longer exists in chibios?  Has any run into this issue and identified a fix? Thank you

**Comment by lesshonor** [comment]
Looks like you [figured out how to update the obsolete out-of-tree code](https://github.com/thompson-vii/kb16_rev2_vial_fw/pull/23), so this issue can be closed.

**Comment by aluminum-ice** [comment]
Resolved in my fork. Closing.
