### ISSUE TITLE
How to use custom tap_dance_actions? 

### ISSUE THREAD

**Issue by uuhan** [vial-kb/vial-qmk#579]
I am migrating my qmk keyboard code to vial, and I have a bunch of `ACTION_TAP_DANCE_FN_ADVANCED`, so I want to use my custom actions:

```c
tap_dance_action_t tap_dance_actions[] = {
    ...
}
```

But it seems the user defined `tap_dance_actions` will conflict the one in vial.c, so how can I disable the one in vial and use my own one?

**Comment by xyzz** [comment]
This is not supported with Vial.
