### ISSUE TITLE
User defined keys

### ISSUE THREAD

**Issue by fjloma** [vial-kb/vial-qmk#623]
I tried to write a custom keycode following the instructions (https://get.vial.today/manual/custom_keycode.html), replacing SAFE_RANGE with USER00 , but failed to compile because USER00 is undefined on vial/keymap.c

Are this instructions correct today or do I need to include some file?

Thanks !

**Comment by xyzz** [comment]
The instructions are indeed out of date, I've fixed it now - you should be using `QK_KB_0` instead of `USER00`.
