### ISSUE TITLE
Nuphy keyboard

### ISSUE THREAD

**Issue by MoroJr** [vial-kb/vial-qmk#650]
Can you add support for Nuphy Air 75 v2?

https://nuphy.com/products/air75-v2

**Comment by adophoxia** [comment]
@MoroJr, to copy this from the issue template for the `qmk/qmk_firmware` as this is also relevant:
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
> Your best bet is to take the initiative, add support, then submit a PR yourself.

And considering how the PR to add this board in `qmk/qmk_firmware` is going, it might be some time before this'll happen. To add to that, historically, in order for a board to be merged into `vial-kb/vial/qmk`, it has to be first merged into `qmk/qmk_firmware` so as to reduce/not deal with any merge conflicts when the Vial fork merges from upstream QMK.

**Comment by roryokane** [comment]
For reference, upstream QMK’s pull request: https://github.com/qmk/qmk_firmware/pull/22751
