### ISSUE TITLE
multiple definition of `key_combos'

### ISSUE THREAD

**Issue by andrewlphilpott** [vial-kb/vial-qmk#668]
Is there a way to get combos working in the default keymap? I'm trying to add one based on how it's shown in the [QMK docs](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_combo.md#combos) (I'm just copy/pasting their first example into my `keymap.c` file).

When I try to compile I get `multiple definition of 'key_combos'`.

I do have `COMBO_ENABLE = yes` in my `rules.mk` but is there something else I need to do as well?

Full error message below:

```
Linking: .build/qazimodo_default.elf                                                                [ERRORS]
 | 
 | /usr/local/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: .build/obj_qazimodo_default/quantum/vial.o:/Users/andrewphilpott/Repos/vial-qmk/quantum/vial.c:509: multiple definition of `key_combos'; .build/obj_qazimodo_default/quantum/keymap_introspection.o:/Users/andrewphilpott/Repos/vial-qmk/./keyboards/qazimodo/keymaps/default/keymap.c:57: first defined here
 | collect2: error: ld returned 1 exit status
 | 
gmake: *** [builddefs/common_rules.mk:283: .build/qazimodo_default.elf] Error 1
```

**Comment by andrewlphilpott** [comment]
Also, should have put this in the original post but I can get combos to work through the Vial GUI. Just can't get it to compile if I try to add any in the `keymap.c`.

**Comment by andrewlphilpott** [comment]
Okay after doing some experimenting, I'm able to get QMK to compile if I disable Vial. So I'm assuming that means adding default combos to the keymap is not supported with Vial.

**Comment by xyzz** [comment]
Yes, manually defining combos is not supported in the "vial" keymap since it conflicts with Vial's dynamic combos.

**Comment by Lefuneste83** [comment]
Yes you just need to get rid of the combos entries in your keymap.c, then define a nice number of vial combos entries using

`#define VIAL_COMBO_ENTRIES xx `(my choice is 25) in your config.h **at keymap level**  (best practice)

Then flash your KB and launch Vial. Then go to the Combos tab and define your combos. 

![image](https://github.com/user-attachments/assets/27786b83-e897-4609-8579-b8aa80cddcae)


**Don't forget to save your KB settings for future flashing as these will be reset every time you update your FW!**
