### ISSUE TITLE
[Bug] GH60 Rev C Vial Incorrect keymap caused hybrid keys

### ISSUE THREAD

**Issue by nlnjnj** [vial-kb/vial-qmk#673]
Issue

The right top key（usualy as `~`）does not work with Vial firmware when choose “Split Backspace” layout.

Root Cause
The root cause is straightforward: Incorrect keymap JSON

![%84S1WGCOJQ3$TU44~0ZS$Y](https://github.com/vial-kb/vial-qmk/assets/5831940/3c799ece-102a-4138-bd55-8de66cf5beb5)

![5TY`R P%2ZF)KRGEVMO H1O](https://github.com/vial-kb/vial-qmk/assets/5831940/d3c4fda7-1626-4fec-ae46-5089f436964f)

**Comment by juanlufont** [comment]
Hi! I created that `vial.json` with the wrong code for the split backspace, sorry!

I have created a MR to fix it: https://github.com/vial-kb/vial-qmk/pull/679
