### ISSUE TITLE
Vial support for Splitkb Kyria rev1

### ISSUE THREAD

**Issue by arthurlutz** [vial-kb/vial-qmk#695]
Sorry, I'm a bit new to this space. Here is a ticket to follow the support for the splitkb / kyria / rev1

If I understand correctly by the https://firmware.splitkb.com/ which doesn't have a vial-qmk firmware and the fact that there are no VIA_ENABLE or VIAL_ENABLE variables in the rules.mk in https://github.com/vial-kb/vial-qmk/tree/vial/keyboards/splitkb/kyria/rev1 that means that only rev3 of splitkb/kyria is supported in VIA. 

Before I spend some time seeing if I can port vial to this particular keyboard, feel free to tell me if it's possible or not (there might be some constraints I don't understand yet).

**Comment by NCKiser** [comment]
It should be possible, go for it!

**Comment by arthurlutz** [comment]
Hi @xyzz I'm not quite sure I understand why you closed this issue. Do you consider this keyboard to have support for VIAL ? I'm looking into porting it as suggested by @NCKiser .
