### ISSUE TITLE
[feature] Keybinds for API triggers

### ISSUE THREAD

**Issue by gbdlin** [vial-kb/vial-qmk#737]
### Rationale
Currently, user is limited to use keys available in the standard keymap on every OS, which is limiting when implementing for example a macropad. Some may use additional key combinations, but they may often conflict with user holding a specific key down while using macropad + has other limitations when trying to combine macros together.

### Solution
Add a special keycode that will not trigger any keypress, but instead it'll output specific message to the rawhid endpoint that a specific key was pressed. Options for the exact message are:

- user-specified code or message, assigned to the key with the mentioned above keycode
- Position of the pressed key on the matrix + optionally current layer
- ...

This way, any software allowed to listen on the rawhid endpoint can react to those special events and implement any desired functionality this way, without conflicting with any keypressed handled by OS or other software. If nothing listens on the endpoint, keys will simply do nothing.

### Security considerations
This keycode should be only assignable in unlocked mode, as attacker could replace all keybinds with this keycode to gain keylogging functionality.

**Comment by xyzz** [comment]
please use https://feedback.vial.today for feature requests

**Comment by gbdlin** [comment]
It would be nice to put it in some contribution guide in repository root, so it's easier to find
