### ISSUE TITLE
Support for Keychron K2 Pro?

### ISSUE THREAD

**Issue by Mateusz-Grzelinski** [vial-kb/vial-qmk#812]
Hi, I have keyboard Keychron K2 Pro and I noticed that Vial does not work with this model.

I can see that there is some support for Keychron keyboards (for example [C1 Pro](https://github.com/vial-kb/vial-qmk/tree/vial/keyboards/keychron/c1_pro)) but I do not know how to make it work. 

Is there any way you can add support for this keyboard?

**Comment by xyzz** [comment]
Vial does not accept requests to add support for any keyboard
