### ISSUE TITLE
[Bug] No OLED on Sofle keyboard

### ISSUE THREAD

**Issue by ricrug** [vial-kb/vial-qmk#94]
After flashing the keyboard with the firmware vial, the displays stay off when switching on.

 - Keyboard:  Sofle
 - Operating system: Linux
 - AVR GCC version: 10.2.0
 - ARM GCC version: 10.2.0

**Comment by xyzz** [comment]
@kirbysayshi could you take a look?

**Comment by kirbysayshi** [comment]
I’ve used this for both sofle v1 and v2, and the OLEDs have worked for both. Could it be a seating or connection issue? Do the OLEDs work when using QMK or via?

**Comment by ricrug** [comment]
> I’ve used this for both sofle v1 and v2, and the OLEDs have worked for both. Could it be a seating or connection issue? Do the OLEDs work when using QMK or via?

yes, it works correctly with via and the default firmware.
Mine is a sofle v2. We tried it in two, on two different keyboards and from two different PCs.

**Comment by kirbysayshi** [comment]
My only guess is that vial changed the OLED interface and now the hook is not being called: https://github.com/vial-kb/vial-qmk/commit/9d235d4fc5c34f372b0c393f41686b5ef4f8dc13#diff-183c0f65ab3d6e9b42d26f0ce05abd45affc4d1a415d6753cdcf09d3271e6a9dR41

if you change oled.h in Sofle to return bool I bet it will work: https://github.com/vial-kb/vial-qmk/blob/7c1e1ddf53d1b077e995b23ed399e791a5e6dbcd/keyboards/sofle/keymaps/vial/oled.c#L76

**Comment by ricrug** [comment]
I think... it is not the only change... there's somthing wrong in the define (I forced it manually into oled.c) and it works... 
I'm still not able to change the logo... even if I changed the qmk_logo array.

**Comment by xyzz** [comment]
Should be fixed by #136
